apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-backend-deployment
spec:
  selector:
    matchLabels:
      app: review-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: review-backend
    spec:
      containers:
        - image: quzicheng/review-backend:0.1
          name: review-backend-con
