apiVersion: v1
kind: Service
metadata:
  name: review-backend-service
  labels:
    app: review-backend
spec:
  type: NodePort
  selector:
      app: review-backend
  ports:
  - protocol : TCP
    nodePort: 30901
    port: 8080
    targetPort: 8080