mindspore:
  version:
    - master
    - r2.8
    - r2.9
    - r2.10

mindspore-lite:
  version:
    - master
    - r2.8
    - r2.9
    - r2.10

mindformers:
  version:
    - master
    - r1.8.0
    - r1.9.0
akg:
  version:
    - master

mindarmour:
  version:
    - master

mindscience:
  version:
    - master

vllm-mindspore:
  version:
    - master

golden-stick:
  version:
    - master

ms_kernels_internal:
  version:
    - master

others:
  version:
    - master

dvm:
  version:
    - master
